### ISSUE TITLE
配置ldap的时候出现报500错误

### ISSUE THREAD

**Issue by zengyunlong** [opendevops-cn/opendevops#24]
HTTPServerRequest(protocol='http', host='mg.domain.com:8010', method='POST', uri='/v2/sysconfig/check/', version='HTTP/1.0', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 296, in wrapper
        result = func(*args, **kwargs)
      File "/usr/local/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/var/www/codo-admin/mg/handlers/app_settings_handler.py", line 88, in post
        ldap_ssl)
      File "/usr/local/lib/python3.6/site-packages/websdk/ldap.py", line 18, in __init__
        self.ldap_server = Server(ldap_server_host, port=ldap_server_port, use_ssl=ldap_use_ssl)
      File "/usr/local/lib/python3.6/site-packages/ldap3/core/server.py", line 86, in __init__
        host = host.strip()
    AttributeError: 'NoneType' object has no attribute 'strip'

感觉像是host参数没有传入，不知道是哪儿配置有问题，麻烦帮忙看看，十分感谢

**Comment by zengyunlong** [comment]
是要先提交才能点测试
